services:
  - type: web
    name: society-management-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma db push
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: society-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: society-management-db
    plan: free
    databaseName: society_management

