import { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
}

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav - Tenant Admin
    'nav.overview': 'Overview',
    'nav.members': 'Members',
    'nav.payments': 'Payments',
    'nav.ledger': 'Ledger Dates',
    'nav.upcoming': 'Upcoming Dues',
    'nav.expenses': 'Expenses',
    'nav.helpdesk': 'Helpdesk',
    'nav.vendors': 'Vendors',
    'nav.events': 'Society Events',
    'nav.notifications': 'Raise Notifications',
    'nav.settings': 'Settings',
    'nav.staff': 'Office Bearers',
    'nav.logs': 'Audit Logs',
    'nav.reports': 'Reports',
    // Nav - Member
    'nav.home': 'My Home',
    'nav.dues_history': 'Maintenance Fee History',
    'nav.payment_history': 'Payment History',
    'nav.receipts': 'Receipts',
    'nav.my_profile': 'My Profile',
    // Header - Tenant Admin
    'header.admin_dashboard': 'Admin Dashboard',
    'header.treasurer_dashboard': 'Treasurer Dashboard',
    'header.society_dashboard': 'Society Dashboard',
    'header.welcome': 'Welcome',
    'header.transfer_cash': 'Transfer Cash',
    'header.record_payment': 'Record Payment',
    'header.logout': 'Logout',
    'header.edit': 'Edit',
    // Header - Member
    'header.resident_portal': 'Resident Portal',
    // Language
    'lang.select': 'Language',
    'lang.en': 'English',
    'lang.ta': 'Tamil',
    // Common actions
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.add': 'Add',
    'action.update': 'Update',
    'action.search': 'Search',
    'action.download': 'Download',
    'action.export': 'Export Excel',
    'action.print': 'Print',
    'action.close': 'Close',
    'action.submit': 'Submit',
    'action.view': 'View',
    'action.remove': 'Remove',
    'action.send': 'Send',
    'action.loading': 'Loading...',
    'action.saving': 'Saving...',
    // Members
    'members.title': 'Members',
    'members.add': 'Add Member',
    'members.add_new': 'Add New Member',
    'members.flat_no': 'Flat / Unit No',
    'members.name': 'Name',
    'members.mobile': 'Mobile',
    'members.email': 'Email',
    'members.paid_until': 'Paid Until',
    'members.outstanding_dues': 'Outstanding Dues',
    'members.status': 'Status',
    'members.actions': 'Actions',
    'members.no_record': 'No Record',
    'members.search': 'Search members...',
    'members.residence_type': 'Residence Type',
    'members.full_name': 'Full Name',
    'members.password': 'Password',
    'members.update': 'Update Member',
    // Payments
    'payments.title': 'Payments',
    'payments.record': 'Record Payment',
    'payments.history': 'Payment History',
    'payments.receipt': 'Payment Receipt',
    'payments.receipt_no': 'Receipt Number',
    'payments.period': 'Payment Period',
    'payments.mode': 'Payment Mode',
    'payments.base_amount': 'Base Amount',
    'payments.late_fee': 'Late Fee',
    'payments.total': 'Total Amount',
    'payments.early_discount': 'Early Bird Discount',
    'payments.date': 'Date',
    'payments.no_records': 'No payment records found.',
    'payments.member': 'Member',
    'payments.amount': 'Amount',
    'payments.received_from': 'Received From',
    'payments.category': 'Category',
    'payments.early_discount_applied': '✓ Early payment discount of ₹{discount} applied!',
    'payments.late_fee_charged': '⚠️ Late fee of ₹{fee} charged!',
    'payments.dues_cleared_msg': '({amount} dues will be cleared)',
    'payments.late_fee_charged_detail': '⚠️ Late fee of ₹{charge} charged {detail}',
    'payments.months_count_detail': '({count} months * ₹{amount}/month default)',
    'payments.flat_default': '(flat default)',
    // Expenses
    'expenses.title': 'Expense Ledger',
    'expenses.add': 'Add Expense',
    'expenses.no_records': 'No expenses recorded yet.',
    'expenses.category': 'Category',
    'expenses.vendor': 'Vendor',
    'expenses.recurring': 'Recurring',
    // Vendors
    'vendors.title': 'Vendors & Service Providers',
    'vendors.add': 'Add Vendor',
    'vendors.name': 'Vendor / Company Name',
    'vendors.service_type': 'Service Type',
    'vendors.phone': 'Phone / Mobile',
    'vendors.notes': 'Notes',
    // Staff
    'staff.title': 'Office Bearers & Staff',
    'staff.add': 'Add Office Bearer',
    'staff.designation': 'Designation',
    // Overview / Dashboard
    'overview.total_income': 'Total Income',
    'overview.total_expenses': 'Total Expenses',
    'overview.net_balance': 'Net Balance',
    'overview.total_members': 'Total Members',
    'overview.members_with_dues': 'Members with Dues',
    'overview.cash_in_hand': 'Cash in Hand',
    'overview.this_month': 'This Month',
    'overview.recent_payments': 'Recent Payments',
    // Member portal overview
    'member.hello': 'Hello',
    'member.welcome': 'Welcome to your resident portal for',
    'member.current_dues': 'Current Dues',
    'member.due_months': 'Due Months',
    'member.flat_details': 'Flat Details',
    'member.annual_cost': 'Annual Maintenance Cost',
    'member.no_dues': 'No outstanding dues!',
    'member.pay_online': 'pay online now',
    'member.all_paid': 'All months paid!',
    'member.unit': 'Unit',
    'member.pending_months': 'month(s) pending payment',
    'member.no_pending': 'No pending months',
    'member.flat': 'Flat',
    // Profile
    'profile.edit': 'Edit Profile',
    'profile.full_name': 'Full Name',
    'profile.flat_no': 'Flat Number',
    'profile.billing_cycle': 'Billing Cycle',
    'profile.address': 'Address',
    'profile.phone': 'Phone Number',
    'profile.new_password': 'New Password',
    'profile.confirm_password': 'Confirm New Password',
    'profile.save_changes': 'Save Changes',
    'profile.security': 'Security & Contact Info',
    'profile.leave_blank': 'Leave blank to keep current password',
    'profile.change_photo': 'Change Photo',
    'profile.upload_photo': 'Upload Photo',
    // Helpdesk
    'helpdesk.my_tickets': 'My Tickets',
    'helpdesk.new_ticket': 'New Ticket',
    'helpdesk.raise_ticket': 'Raise New Ticket',
    'helpdesk.subject': 'Subject',
    'helpdesk.description': 'Description',
    'helpdesk.priority': 'Priority',
    'helpdesk.submit': 'Submit Ticket',
    'helpdesk.add_reply': 'Add a reply...',
    'helpdesk.select_ticket': 'Select a ticket to view conversation',
    'helpdesk.no_tickets': 'No tickets raised yet.',
    'helpdesk.attachment': 'Attachment (Optional Image)',
    // Settings
    'settings.title': 'Settings',
    'settings.pricing': 'Pricing',
    'settings.reminders': 'Reminders',
    'settings.general': 'General',
    // Status
    'status.paid': 'Paid',
    'status.overdue': 'Overdue',
    'status.due_this_month': 'Due This Month',
    'status.cancelled': 'Cancelled',
    'status.open': 'Open',
    'status.resolved': 'Resolved',
    'status.closed': 'Closed',
    // Events
    'events.title': 'Society Events',
    'events.no_events': 'No upcoming events.',
    // Reports
    'reports.title': 'Financial Reports',
    'reports.export': 'Export as Excel',
    'reports.apply_filter': 'Apply Filter',
    'reports.period_income': 'Period Income',
    'reports.period_expenses': 'Period Expenses',
    // Upcoming dues
    'upcoming.title': 'Upcoming Dues',
    'upcoming.member': 'Member',
    'upcoming.paid_until': 'Paid Until',
    'upcoming.outstanding': 'Outstanding Dues',
    'upcoming.no_records': 'No upcoming or overdue payments! All members are paid up.',
    // Audit logs
    'logs.title': 'Audit Logs',
    // Notifications
    'notify.title': 'Send Notification',
    'notify.send': 'Send to Member',
    'notify.broadcast': 'Broadcast Notification',
    // Cash handover
    'cash.handover_request': 'Cash Handover Request',
    'cash.accept': 'Accept & Update Balance',
    'cash.wants_handover': 'wants to handover',
    'cash.to_you': 'to you.',
    // Ledger
    'ledger.title': 'Ledger Payment Dates',

    // Staff Management
    'staff.manage_desc': 'Manage treasurers, secretaries, and committee members who can log in to this portal.',
    'staff.no_bearers': 'No office bearers added yet. Add your first treasurer or secretary.',
    'staff.add_bearer': 'Add Office Bearer',
    'staff.edit_bearer': 'Edit Office Bearer',
    'staff.add_new_bearer': 'Add New Office Bearer',
    'staff.full_name': 'Full Name *',
    'staff.email': 'Email *',
    'staff.mobile': 'Mobile *',
    'staff.password_label_edit': 'New Password (leave blank to keep)',
    'staff.password_label_new': 'Password *',
    'staff.flat_no_optional': 'Flat Number (Optional)',
    'staff.also_add_member': 'Also add this office bearer as a society member (displays in member list)',
    'staff.associated_details': 'Associated Member Profile Details',
    'staff.residence_type': 'Residence Type *',
    'staff.bhk_option': 'BHK Option *',
    'staff.bhk_specify': 'Specify BHK',
    'staff.bhk_option_label': 'BHK Option',
    'staff.enable_common_maintenance': 'Enable common maintenance (if checked, charges the common value instead of BHK value)',
    'staff.error_name': 'Full Name is required',
    'staff.error_email': 'Email is required',
    'staff.error_mobile': 'Mobile number is required',
    'staff.error_mobile_digits': 'Mobile number must be exactly 10 digits',
    'staff.error_bhk': 'Please enter BHK value',
    'staff.confirm_delete_title': 'Remove Office Bearer',
    'staff.confirm_delete_msg': 'Are you sure you want to remove "{name}" from office bearers?',
    'staff.confirm_linked_title': 'Remove Linked Member Profile',
    'staff.confirm_linked_msg': '"{name}" is also registered as a member.\n\nDo you want to remove them from the Members list as well?\n• Click OK to remove from BOTH (Office Bearer & Member)\n• Click Cancel to remove ONLY as Office Bearer (keeps them as Member)',
    'staff.remove_both': 'Remove from BOTH',
    'staff.remove_only_staff': 'Remove ONLY as Office Bearer',

    // Vendor Management
    'vendors.registered': '{count} vendor{suffix} registered',
    'vendors.edit': 'Edit Vendor',
    'vendors.add_new': 'Add New Vendor',
    'vendors.name_label': 'Vendor / Company Name *',
    'vendors.phone_label': 'Phone / Mobile',
    'vendors.email_label': 'Email',
    'vendors.address_label': 'Address',
    'vendors.notes_label': 'Notes',
    'vendors.error_name': 'Vendor name is required',
    'vendors.error_phone': 'Contact/Mobile number must be exactly 10 digits',
    'vendors.confirm_delete_title': 'Delete Vendor',
    'vendors.confirm_delete_msg': 'Delete vendor "{name}"? This may affect linked expenses.',
    'vendors.no_vendors': 'No vendors added yet. Add your plumbers, electricians, and other service providers.',

    // Expense Management
    'expenses.edit': 'Edit Expense',
    'expenses.new': 'New Expense',
    'expenses.title_label': 'Title *',
    'expenses.category_label': 'Category *',
    'expenses.amount_label': 'Amount (₹) *',
    'expenses.date_label': 'Date *',
    'expenses.payment_mode_label': 'Payment Mode *',
    'expenses.payment_mode_cash': 'Cash (deducts from Cash in Hand)',
    'expenses.payment_mode_bank': 'Bank Transfer',
    'expenses.vendor_label': 'Vendor (optional)',
    'expenses.no_vendor': '— No Vendor —',
    'expenses.paid_by_member': 'Paid By Member (Reimbursement Claim)',
    'expenses.select_member': 'Select Member',
    'expenses.no_member_society': '— No (Paid by Society) —',
    'expenses.reimbursement_method': 'Reimbursement Method',
    'expenses.offset_dues': 'Offset Dues (Advance Paid-Until)',
    'expenses.cash_refund': 'Cash Refund (Deduct Society Cash)',
    'expenses.notes_optional': 'Notes (optional)',
    'expenses.mark_recurring': 'Mark as recurring expense (monthly)',
    'expenses.total_amount': 'Total: ',
    'expenses.no_records_desc': 'No expenses recorded yet. Click "Add Expense" to get started.',
    'expenses.confirm_delete_title': 'Delete Expense',
    'expenses.confirm_delete_msg': 'Delete this expense?',
    'expenses.error_title': 'Title is required',
    'expenses.error_amount': 'Enter a valid amount',
    'expenses.error_delete': 'Error deleting expense',

    // Settings / Financial Cost Setup
    'settings.fy_cost_setup': 'Financial Year - Annual Fee Setup',
    'settings.fy_cost_desc': 'Set different annual fees per BHK type for Flat and Villa. Each combination (Residence Type + BHK) can have its own fee.',
    'settings.financial_year': 'Financial Year',
    'settings.residence_type': 'Residence Type',
    'settings.residence_common': 'Common (all members)',
    'settings.residence_flat': 'Flat',
    'settings.residence_villa': 'Villa',
    'settings.annual_fee': 'Annual Fee (Rs.)',
    'settings.set_bhk_fees': 'Set Annual Fees for {residenceType} by BHK Type',
    'settings.bhk_fees_desc': 'Specify the annual fee for each BHK type. Empty or 0 values will not be updated/configured.',
    'settings.bhk_fee_label': '{bhk} BHK Fee (Rs.)',
    'settings.custom_bhk_fees': 'Custom BHK Fees (optional)',
    'settings.add_custom_bhk': '+ Add Custom BHK',
    'settings.set_annual_fees': 'Set Annual Fees',
    'settings.configured_annual_fees': 'Configured Annual Fees',
    'settings.no_fees_configured': 'No fees configured yet. Use the form above to get started.',
    'settings.common': 'Common',
    'settings.flat_by_bhk': 'Flat - by BHK',
    'settings.villa_by_bhk': 'Villa - by BHK',
    'settings.delete_config_title': 'Delete Pricing Configuration',
    'settings.delete_config_msg': 'Are you sure you want to delete this configuration?',
    'settings.select_fy_error': 'Please select a financial year',
    'settings.invalid_amount_error': 'Please enter a valid amount',
    'settings.specify_bhk_error': 'Please specify fee amount for at least one BHK type',
    'settings.config_success': 'Maintenance cost(s) configured successfully',
    'settings.config_deleted_success': 'Configuration deleted successfully',

    // Masters Management
    'masters.title': 'Data Masters',
    'masters.desc': 'Manage the dropdown values used across the system.',
    'masters.service_types': 'Vendor Service Types',
    'masters.service_types_desc': 'Types of services vendors can provide (e.g. Plumbing, Electrical)',
    'masters.designations': 'Staff Designations',
    'masters.designations_desc': 'Titles for office bearers (e.g. Treasurer, Secretary)',
    'masters.expense_categories': 'Expense Categories',
    'masters.expense_categories_desc': 'Categories for classifying expenses (e.g. Repairs, Utilities)',
    'masters.delete_title': 'Remove Master Item',
    'masters.delete_msg': 'Remove "{value}" from the list?',
    'masters.no_items': 'No items yet. Add your first one above.',

    // Helpdesk
    'helpdesk.all_status': 'All Status',
    'helpdesk.status_open': 'Open',
    'helpdesk.status_in_progress': 'In Progress',
    'helpdesk.status_resolved': 'Resolved',
    'helpdesk.status_closed': 'Closed',
    'helpdesk.status_archived': 'Archived',
    'helpdesk.raised_by': 'Raised by: ',
    'helpdesk.attached_image': 'Attached Image',
    'helpdesk.no_discussions': 'No discussions yet. Start the conversation below.',
    'helpdesk.type_response': 'Type your response here...',
    'helpdesk.reply': 'Reply',
    'helpdesk.delete_ticket_title': 'Delete Helpdesk Ticket',
    'helpdesk.delete_ticket_msg': 'Are you sure you want to permanently delete this ticket and all its discussions?',
    'helpdesk.manage_desc': 'Manage society concerns and member requests from this portal.',

    // Profile
    'profile.my_profile': 'My Profile & Password',
    'profile.name': 'Name',
    'profile.designation': 'Designation',
    'profile.email': 'Email Address',
    'profile.mobile': 'Mobile Number',
    'profile.save_btn': 'Save Profile & Password',
    'profile.primary_admin': 'Primary Admin',

    // Events
    'events.desc': 'Schedule and manage events/meetings in the society. Creating an event automatically sends a notification to all members.',
    'events.add': 'Add Event',
    'events.edit': 'Edit Event',
    'events.create_new': 'Create New Event',
    'events.title_label': 'Event Title *',
    'events.date_label': 'Event Date & Time *',
    'events.location_label': 'Location / Venue',
    'events.desc_label': 'Event Description *',
    'events.venue': 'Venue',
    'events.no_events_desc': 'No upcoming events scheduled yet. Click "Add Event" to create one.',
    'events.delete_title': 'Delete Event',
    'events.delete_msg': 'Are you sure you want to delete the event "{title}"?',
    'events.error_required': 'Title, description, and date are required.',
    'events.success_update': 'Event updated successfully!',
    'events.success_create': 'Event created and members notified successfully!',
    'events.success_delete': 'Event deleted successfully!',
    'events.error_delete': 'Error deleting event',

    // Notifications
    'notify.send_manual': 'Send Manual Notification',
    'notify.manual_desc': 'Send a targeted notification to a specific member or broadcast to all society members.',
    'notify.send_to': 'Send To *',
    'notify.all_members': '📢 All Members (Broadcast)',
    'notify.specific_member': '👤 Specific Member',
    'notify.select_member_label': 'Select Member *',
    'notify.title_label': 'Notification Title *',
    'notify.message_label': 'Description / Message *',
    'notify.monthly_reminders': 'Monthly Dues Reminders',
    'notify.monthly_reminders_desc': 'Automatically runs on the 1st of every month. You can also trigger it manually now — only members with outstanding dues will be notified.',
    'notify.send_now': 'Send Dues Reminders Now',
    'notify.paid_warning_title': 'Member May Have Paid Already',
    'notify.cancel_dont_send': 'Cancel — Don\'t Send',
    'notify.send_anyway': 'Send Anyway',

    // Members Modals
    'members.register_desc': 'Register a new resident and set up their portal access',
    'members.general_details': '01. General Details',
    'members.contact_access': '02. Contact & Access',
    'members.document_uploads': '03. Document Uploads',
    'members.initial_setup': '04. Initial Setup / Corpus Fund',
    'members.custom_bhk': 'Custom BHK *',
    'members.enable_common_maintenance': 'Enable Common Maintenance',
    'members.default_tenure': 'Default Payment Tenure *',
    'members.active_from': 'Membership Active From',
    'members.next_cycle_desc': 'Next payment cycle will start from this date.',
    'members.old_dues': 'Old Pending Dues (₹)',
    'members.reg_year': 'Registration Year *',
    'members.primary_contact': 'Primary Contact (Compulsory)',
    'members.primary_number': 'Primary Number *',
    'members.primary_email': 'Primary Email (Optional)',
    'members.set_primary_password': 'Set Primary Login Password (Optional)',
    'members.primary_password_desc': 'Setting a password enables member portal login for the primary contact via mobile or email.',
    'members.secondary_contact': 'Secondary Contact (Optional)',
    'members.secondary_number': 'Secondary Number (Optional)',
    'members.secondary_email': 'Secondary Email (Optional)',
    'members.set_secondary_password': 'Set Secondary Login Password (Optional)',
    'members.secondary_password_desc': 'Setting a password enables member portal login for the secondary contact via mobile or email.',
    'members.id_proof': 'ID Proof (Aadhar/PAN)',
    'members.uploaded_id': 'Uploaded ID Document',
    'members.upload_image': 'Upload Image/Photo',
    'members.upload_pdf': 'Upload PDF Document',
    'members.uploading_wait': '⏳ Uploading document, please wait...',
    'members.initial_payment': 'Initial Payment (₹)',
    'members.payment_mode': 'Payment Mode',
    'members.payment_date': 'Payment Date',
    'members.payment_notes': 'Payment Notes',
    'members.add_btn': 'Add Member',
    'members.edit_details': 'Edit Member Details',
    'members.edit_desc': 'Modify flat occupant profile, credentials, and documentation',
    'members.status_label': 'Status *',
    'members.paid_until_label': 'Paid Until (Period Covered)',
    'members.next_cycle_edit_desc': 'Next payment cycle will start after this date.',
    'members.outstanding_dues_label': 'Outstanding Dues (₹)',
    'members.outstanding_dues_desc': 'Current unpaid balance/dues for this member.',
    'members.change_primary_password': 'Change Primary Login Password (Optional)',
    'members.password_update_desc': 'Password will be updated only if you enter a new one.',
    'members.change_secondary_password': 'Change Secondary Login Password (Optional)',
    'members.update_btn': 'Update Member',

    // Payments Modals
    'payments.choose_member': '-- Choose Member --',
    'payments.click_select': 'Click to select',
    'payments.monthly': 'Monthly',
    'payments.quarterly': 'Quarterly',
    'payments.half_yearly': 'Half-Yearly',
    'payments.annual': 'Annual',
    'payments.received_date': 'Payment Date Received from Member',
    'payments.amount_received': 'Amount Received (₹)',
    'payments.early_discount_label': 'Early Bird Discount (₹)',
    'payments.late_fee_label': 'Late Fee (₹)',
    'payments.total_amount_label': 'Total Amount (₹)',
    'payments.ledger_date': 'Payment Date Recorded in Ledger',
    'payments.notes_placeholder': 'e.g. Receipt No, Transaction ID',
    'payments.custom_coverage': 'Advanced: Custom Coverage Dates',
    'payments.coverage_desc': 'Leave blank to auto-calculate based on current paid-until date.',
    'payments.coverage_start': 'Coverage Start (Optional)',
    'payments.coverage_end': 'Coverage End (Optional)',
    'payments.current_cash': 'Your Current Cash Balance',
    'payments.transfer_type': 'Transfer Type',
    'payments.handover_to_admin': 'Handover to Admin',
    'payments.deposit_to_bank': 'Deposit to Bank',
    'payments.select_recipient': 'Select Recipient Admin',
    'payments.select_treasurer': '-- Select Treasurer --',
    'payments.initiate_transfer': 'Initiate Transfer',

    // New common / status keys
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'common.optional': 'Optional',
    'common.image': 'IMAGE',
    'common.pdf': 'PDF',

    // New overview / dashboard keys
    'overview.total_collection': 'Total Collection',
    'overview.this_month_income': 'This month: ₹{amount}',
    'overview.this_month_expense': 'This month: ₹{amount}',
    'overview.collection_expenses': 'Collection – Expenses',
    'overview.your_share': 'Your share: ₹{amount}',
    'overview.vs_last_month': 'vs last month',
    'overview.financial_recon': 'Financial Reconciliation',
    'overview.all_payment_modes': 'All payment modes',
    'overview.all_recorded_expenses': 'All recorded expenses',
    'overview.collected_minus_expenses': 'Collected − Expenses',
    'overview.physical_cash_avail': 'Physical cash available',
    'overview.cash_how_calculated': 'Cash In Hand — How It\'s Calculated',
    'overview.cash_collected': 'Cash Collected',
    'overview.cash_expenses': 'Cash Expenses',
    'overview.bank_deposited': 'Bank Deposited',
    'overview.non_cash_collected': 'Non-Cash (UPI/Bank/Cheque)',
    'overview.outstanding_dues_alert': '{count} member{suffix} have outstanding dues of {amount}',
    'overview.view_members': 'View Members →',
    'overview.six_month_trend': '6-Month Income vs Expense Trend',
    'overview.collection': 'Collection',
    'overview.expenses_label': 'Expenses',
    'overview.net': 'Net',
    'overview.expense_by_cat': 'Expenses by Category',
    'overview.no_expense_recorded': 'No expenses recorded yet',
    'overview.recent_collections': 'Recent Collections',
    'overview.no_payment_recorded': 'No payments recorded yet.',
    'overview.cash_holders': 'Cash In Hand — Holders',
    'overview.no_cash_data': 'No cash balance data available.',
    'overview.you': 'You',
    'overview.total': 'Total',

    // New members keys
    'members.society_members': 'Society Members',
    'members.search_placeholder': 'Search name, flat, mobile...',
    'members.export_excel': 'Export Excel',
    'members.template': 'Template',
    'members.bulk_import': 'Bulk Import',
    'members.contact_info': 'Contact Info',
    'members.no_matching_found': 'No matching members found',
    'members.widen_search': 'Try widening your search terms or clearing the search query',
    'members.photo': 'Photo',
    'members.id_proof_tag': 'ID Proof',
    'members.click_view_photo': 'Click to view profile photo',
    'members.click_view_id': 'Click to view ID proof',
    'members.no_email': 'No email',
    'members.no_fy_fee': 'No FY fee',
    'members.unpaid_periods_msg': '{count} {period} @ {rate}',
    'members.history_btn': 'History',
    'members.mark_vacant': 'Mark Flat as Vacant',
    'members.vacated_pending_dues': 'Vacated Members with Pending Dues',
    'members.vacated_pending_desc': 'These members have vacated their flats but still have outstanding dues that need to be collected.',
    'members.other_custom': 'Other / Custom',

    // New payments keys
    'payments.payment_history': 'Payment History',
    'payments.export_excel': 'Export Excel',
    'payments.record_payment': 'Record Payment',
    'payments.onboarding': 'Onboarding',
    'payments.view_receipt': 'View Receipt',
    'payments.edit_payment': 'Edit Payment',
    'payments.cancel_payment': 'Cancel Payment',
    'payments.mode_cash': 'Cash',
    'payments.mode_bank': 'Bank Transfer',
    'payments.mode_upi': 'UPI / QR',
    'payments.mode_cheque': 'Cheque',
    'payments.total_paid': 'Total Paid',
    'payments.outstanding': 'Outstanding',
    'payments.receipts_count': 'Receipts',
    'payments.fy': 'FY',
    'payments.coverage': 'Coverage',
    'payments.status': 'Status',
    'payments.maintenance_receipt': 'Maintenance Fee Receipt',
    'payments.generated_on': 'Generated on',
    'payments.collected_by': 'By',
    'payments.download_pdf': 'Download PDF',
    'payments.select_member': 'Select Member',
    'payments.category_maintenance': 'Maintenance',
    'payments.category_event': 'Event Fee',
    'payments.category_corpus': 'Corpus Fund',
    'payments.category_water': 'Water Dues',
    'payments.category_other': 'Other',
    'payments.notes': 'Reference / Notes',
    'payments.edit_payment_title': 'Edit Payment — {receipt}',
    'payments.transfer_cash': 'Transfer / Handover Cash',
    'payments.transfer_notes_placeholder': 'e.g. For weekly bank deposit',

    // New ledger reconciliation keys
    'ledger.ledger_payment_dates': 'Ledger Payment Dates',
    'ledger.compare_dates_desc': 'Compare the date payment was received from a member vs the date recorded in the ledger.',
    'ledger.received_date_member': 'Received Date (Member)',
    'ledger.recorded_date_ledger': 'Recorded Date (Ledger)',
    'ledger.not_recorded': 'Not recorded',
    'ledger.no_records': 'No payment records found',

    // New reports keys
    'reports.financial_reports': 'Financial Reports',
    'reports.generate_analyze': 'Generate and analyze financial statements',
    'reports.export_excel': 'Export as Excel',
    'reports.month': 'Month',
    'reports.all_months': 'All Months',
    'reports.year': 'Year',
    'reports.start_date': 'Start Date',
    'reports.end_date': 'End Date',
    'reports.period_surplus_deficit': 'Period Surplus / Deficit',
    'reports.balance_sheet_status': 'Balance Sheet Status',
    'reports.balanced': 'Balanced',
    'reports.diff': 'Diff: ₹{amount}',
    'reports.income_expenditure_stmt': 'Income & Expenditure Statement',
    'reports.balance_sheet': 'Balance Sheet',
    'reports.no_transactions': 'No Transactions Found',
    'reports.no_transactions_desc': 'There are no recorded incomes or expenses for the selected period: {period}',
    'reports.dr': 'Dr.',
    'reports.cr': 'Cr.',
    'reports.expenditure': 'Expenditure',
    'reports.income': 'Income',
    'reports.total': 'Total',
    'reports.as_at': 'As At: {date}',
    'reports.liabilities': 'Liabilities',
    'reports.assets': 'Assets',

    // New logs keys
    'logs.audit_logs': 'Audit Logs',
    'logs.of_entries': '{count} of {total} entries',
    'logs.from_date': 'From Date',
    'logs.to_date': 'To Date',
    'logs.office_bearer': 'Office Bearer',
    'logs.all_office_bearers': 'All Office Bearers',
    'logs.show_logs': 'Show Logs',
    'logs.show_all_logs': 'Show All Logs',
    'logs.clear_filters': 'Clear Filters',
    'logs.timestamp': 'Timestamp',
    'logs.user': 'User',
    'logs.action': 'Action',
    'logs.details': 'Details',
    'logs.no_match': 'No audit log entries match your filters.',
    'logs.set_filters_prompt': 'Set filters and click Show Logs',
    'logs.use_filters_desc': 'Use the filters above to narrow down the audit trail, then click the button to load results.',

    // New settings keys
    'settings.settings_hub': 'Settings Hub',
    'settings.config_desc': 'Configure society preferences',
    'settings.pricing_fees': 'Pricing & Fees',
    'settings.auto_reminders': 'Auto-Reminders',
    'settings.early_discount': 'Early Bird Discount',
    'settings.late_fee': 'Late Fee',
    'settings.fy_setup': 'Financial Year Setup',
    'settings.system_masters': 'System Masters',
    'settings.society_settings_pricing': 'Society Settings (Pricing Master)',
    'settings.pricing_desc': 'Define the base rates and pre-calculated discounts for payment plans.',
    'settings.base_monthly': 'Base Monthly Amount (₹)',
    'settings.quarterly_amt': 'Quarterly Amount (₹)',
    'settings.half_yearly_amt': 'Half-Yearly Amount (₹)',
    'settings.annual_amt': 'Annual Amount (₹)',
    'settings.save_pricing': 'Save Pricing Settings',
    'settings.auto_reminder_settings': 'Auto-Reminder Settings',
    'settings.auto_reminder_desc': 'Automate reminder emails and alerts for pending dues.',
    'settings.monthly_maint_reminder': 'Monthly Maintenance Reminder',
    'settings.monthly_reminder_desc': 'Trigger payment reminder notifications for active members automatically at specified intervals during the month.',
    'settings.frequency_times': 'Frequency (Times)',
    'settings.interval_days': 'Interval (Days)',
    'settings.max_times_notify': 'Max times to notify in the billing month.',
    'settings.days_between_reminders': 'Days between reminders.',
    'settings.overdue_dues_reminder': 'Overdue Dues Reminder',
    'settings.overdue_reminder_desc': 'If a member has unpaid outstanding dues, automatically send notifications periodically until dues are cleared.',
    'settings.days_between_overdue_desc': 'Days between reminders. For consecutive unpaid months, monthly email summary alerts are sent.',
    'settings.save_reminders': 'Save Reminder Settings',
    'settings.early_payment_discount': 'Early Payment Discount (Optional)',
    'settings.early_discount_desc': 'Provide a discount to members paying before a selected cut-off date.',
    'settings.discount_cutoff': 'Discount Cut-off Date',
    'settings.discount_cutoff_desc': 'Payments under the \'Maintenance\' category received on or before this date automatically get the discount applied.',
    'settings.discount_amount': 'Discount Amount (₹)',
    'settings.discount_amount_desc': 'Flat amount deducted from the final calculated payment total.',
    'settings.save_discount': 'Save Discount Settings',
    'settings.late_fee_settings': 'Late Fee Settings (Optional)',
    'settings.late_fee_settings_desc': 'Configure late fees for maintenance payments received after a specific cut-off date.',
    'settings.active_late_fee_info': 'Active Settings: Cut-off Day is the {day}th of every month with a late fee of ₹{amount}.',
    'settings.no_active_late_fee': 'No active late fee settings configured. Late fees will not be calculated.',
    'settings.late_fee_cutoff': 'Late Fee Cut-off Date',
    'settings.late_fee_cutoff_desc': 'Payments under the \'Maintenance\' category received after this date automatically incur a late fee.',
    'settings.late_fee_per_month': 'Late Fee Amount per Month (₹)',
    'settings.late_fee_per_month_desc': 'Flat fee charged monthly. For custom coverage dates (e.g. 2026 to 2027), this is multiplied by the number of covered months.',
    'settings.save_late_fee': 'Save Late Fee Settings',

    // New upcoming keys
    'upcoming.upcoming_overdue': 'Upcoming & Overdue Payments',
    'upcoming.monitor_manage': 'Monitor and manage member maintenance dues',
    'upcoming.calculate_dues_by': 'Calculate Dues By:',
    'upcoming.calc_db': 'Outstanding Dues (DB)',
    'upcoming.calc_monthly': 'Monthly Basis',
    'upcoming.calc_quarterly': 'Quarterly Basis',
    'upcoming.calc_half_yearly': 'Half-Yearly Basis',
    'upcoming.calc_annual': 'Annual Basis',
    'upcoming.download_dues_list': 'Download Dues List',
    'upcoming.dynamic_dues_info': 'Showing dynamically calculated dues based on {mode} cycle using the configured annual fees.',
    'upcoming.flat_no_col': 'FLAT NO',
    'upcoming.member_col': 'MEMBER',
    'upcoming.paid_until_col': 'PAID UNTIL',
    'upcoming.outstanding_dues_col': 'OUTSTANDING DUES',
    'upcoming.status_col': 'STATUS',
    'upcoming.annual_fee_not_configured': 'Annual fee not configured for FY {year}',
  },

  ta: {
    // Nav - Tenant Admin
    'nav.overview': 'மேலோட்டம்',
    'nav.members': 'உறுப்பினர்கள்',
    'nav.payments': 'கட்டணங்கள்',
    'nav.ledger': 'பேரேடு தேதிகள்',
    'nav.upcoming': 'வரவிருக்கும் நிலுவைகள்',
    'nav.expenses': 'செலவுகள்',
    'nav.helpdesk': 'உதவி மேசை',
    'nav.vendors': 'சேவையாளர்கள்',
    'nav.events': 'சமூக நிகழ்வுகள்',
    'nav.notifications': 'அறிவிப்புகள் அனுப்பு',
    'nav.settings': 'அமைப்புகள்',
    'nav.staff': 'அலுவல் பொறுப்பாளர்கள்',
    'nav.logs': 'தணிக்கை பதிவுகள்',
    'nav.reports': 'அறிக்கைகள்',
    // Nav - Member
    'nav.home': 'என் முகப்பு',
    'nav.dues_history': 'பராமரிப்பு கட்டண வரலாறு',
    'nav.payment_history': 'கட்டண வரலாறு',
    'nav.receipts': 'ரசீதுகள்',
    'nav.my_profile': 'என் சுயவிவரம்',
    // Header - Tenant Admin
    'header.admin_dashboard': 'நிர்வாக டாஷ்போர்டு',
    'header.treasurer_dashboard': 'கருவூலர் டாஷ்போர்டு',
    'header.society_dashboard': 'சமூக டாஷ்போர்டு',
    'header.welcome': 'வணக்கம்',
    'header.transfer_cash': 'பணம் மாற்று',
    'header.record_payment': 'கட்டணம் பதிவு செய்',
    'header.logout': 'வெளியேறு',
    'header.edit': 'திருத்து',
    // Header - Member
    'header.resident_portal': 'குடியிருப்பாளர் போர்டல்',
    // Language
    'lang.select': 'மொழி',
    'lang.en': 'ஆங்கிலம்',
    'lang.ta': 'தமிழ்',
    // Common actions
    'action.save': 'சேமி',
    'action.cancel': 'ரத்துசெய்',
    'action.edit': 'திருத்து',
    'action.delete': 'நீக்கு',
    'action.add': 'சேர்',
    'action.update': 'புதுப்பி',
    'action.search': 'தேடு',
    'action.download': 'பதிவிறக்கு',
    'action.export': 'எக்செல் ஏற்றுமதி',
    'action.print': 'அச்சிடு',
    'action.close': 'மூடு',
    'action.submit': 'சமர்ப்பி',
    'action.view': 'பார்',
    'action.remove': 'நீக்கு',
    'action.send': 'அனுப்பு',
    'action.loading': 'ஏற்றுகிறது...',
    'action.saving': 'சேமிக்கிறது...',
    // Members
    'members.title': 'உறுப்பினர்கள்',
    'members.add': 'உறுப்பினர் சேர்',
    'members.add_new': 'புதிய உறுப்பினர் சேர்',
    'members.flat_no': 'வீடு / அலகு எண்',
    'members.name': 'பெயர்',
    'members.mobile': 'கைபேசி',
    'members.email': 'மின்னஞ்சல்',
    'members.paid_until': 'வரை செலுத்தப்பட்டது',
    'members.outstanding_dues': 'நிலுவை தொகை',
    'members.status': 'நிலை',
    'members.actions': 'செயல்கள்',
    'members.no_record': 'பதிவு இல்லை',
    'members.search': 'உறுப்பினர்களை தேடு...',
    'members.residence_type': 'வாழ்விட வகை',
    'members.full_name': 'முழு பெயர்',
    'members.password': 'கடவுச்சொல்',
    'members.update': 'உறுப்பினர் புதுப்பி',
    // Payments
    'payments.title': 'கட்டணங்கள்',
    'payments.record': 'கட்டணம் பதிவு செய்',
    'payments.history': 'கட்டண வரலாறு',
    'payments.receipt': 'கட்டண ரசீது',
    'payments.receipt_no': 'ரசீது எண்',
    'payments.period': 'கட்டண காலம்',
    'payments.mode': 'கட்டண முறை',
    'payments.base_amount': 'அடிப்படை தொகை',
    'payments.late_fee': 'தாமத கட்டணம்',
    'payments.total': 'மொத்த தொகை',
    'payments.early_discount': 'முன்கூட்டிய தள்ளுபடி',
    'payments.date': 'தேதி',
    'payments.no_records': 'கட்டண பதிவுகள் எதுவும் இல்லை.',
    'payments.member': 'உறுப்பினர்',
    'payments.amount': 'தொகை',
    'payments.received_from': 'பெறப்பட்டது',
    'payments.category': 'வகை',
    'payments.early_discount_applied': '✓ முன்கூட்டியே செலுத்திய தள்ளுபடி ₹{discount} பயன்படுத்தப்பட்டது!',
    'payments.late_fee_charged': '⚠️ தாமதக் கட்டணம் ₹{fee} வசூலிக்கப்பட்டது!',
    'payments.dues_cleared_msg': '({amount} நிலுவை தொகை சரிசெய்யப்படும்)',
    'payments.late_fee_charged_detail': '⚠️ தாமதக் கட்டணம் ₹{charge} வசூலிக்கப்பட்டது {detail}',
    'payments.months_count_detail': '({count} மாதங்கள் * ₹{amount}/மாதம் இயல்புநிலை)',
    'payments.flat_default': '(நிலையான இயல்புநிலை)',
    // Expenses
    'expenses.title': 'செலவு பதிவேடு',
    'expenses.add': 'செலவு சேர்',
    'expenses.no_records': 'இதுவரை செலவுகள் பதிவு இல்லை.',
    'expenses.category': 'வகை',
    'expenses.vendor': 'சேவையாளர்',
    'expenses.recurring': 'தொடர்ச்சியான',
    // Vendors
    'vendors.title': 'சேவையாளர்கள்',
    'vendors.add': 'சேவையாளர் சேர்',
    'vendors.name': 'சேவையாளர் / நிறுவன பெயர்',
    'vendors.service_type': 'சேவை வகை',
    'vendors.phone': 'தொலைபேசி / கைபேசி',
    'vendors.notes': 'குறிப்புகள்',
    // Staff
    'staff.title': 'அலுவல் பொறுப்பாளர்கள்',
    'staff.add': 'பொறுப்பாளர் சேர்',
    'staff.designation': 'பதவி',
    // Overview
    'overview.total_income': 'மொத்த வருமானம்',
    'overview.total_expenses': 'மொத்த செலவு',
    'overview.net_balance': 'நிகர இருப்பு',
    'overview.total_members': 'மொத்த உறுப்பினர்கள்',
    'overview.members_with_dues': 'நிலுவை உள்ள உறுப்பினர்கள்',
    'overview.cash_in_hand': 'கையிருப்பு பணம்',
    'overview.this_month': 'இந்த மாதம்',
    'overview.recent_payments': 'சமீபத்திய கட்டணங்கள்',
    // Member portal
    'member.hello': 'வணக்கம்',
    'member.welcome': 'உங்கள் குடியிருப்பு போர்டலுக்கு வரவேற்கிறோம்',
    'member.current_dues': 'தற்போதைய நிலுவை',
    'member.due_months': 'நிலுவை மாதங்கள்',
    'member.flat_details': 'வீடு விவரங்கள்',
    'member.annual_cost': 'ஆண்டு பராமரிப்பு செலவு',
    'member.no_dues': 'நிலுவைகள் எதுவும் இல்லை!',
    'member.pay_online': 'இப்போது ஆன்லைனில் செலுத்துங்கள்',
    'member.all_paid': 'அனைத்து மாதங்களும் செலுத்தப்பட்டது!',
    'member.unit': 'அலகு',
    'member.pending_months': 'மாதங்கள் நிலுவையில் உள்ளன',
    'member.no_pending': 'நிலுவை மாதங்கள் இல்லை',
    'member.flat': 'வீடு',
    // Profile
    'profile.edit': 'சுயவிவரம் திருத்து',
    'profile.full_name': 'முழு பெயர்',
    'profile.flat_no': 'வீட்டு எண்',
    'profile.billing_cycle': 'கட்டண சுழற்சி',
    'profile.address': 'முகவரி',
    'profile.phone': 'தொலைபேசி எண்',
    'profile.new_password': 'புதிய கடவுச்சொல்',
    'profile.confirm_password': 'கடவுச்சொல் உறுதிப்படுத்து',
    'profile.save_changes': 'மாற்றங்களை சேமி',
    'profile.security': 'பாதுகாப்பு & தொடர்பு தகவல்',
    'profile.leave_blank': 'தற்போதைய கடவுச்சொல் மாற்றாமல் விட வேண்டுமெனில் காலியாக விடுங்கள்',
    'profile.change_photo': 'புகைப்படம் மாற்று',
    'profile.upload_photo': 'புகைப்படம் பதிவேற்று',
    // Helpdesk
    'helpdesk.my_tickets': 'என் புகார்கள்',
    'helpdesk.new_ticket': 'புதிய புகார்',
    'helpdesk.raise_ticket': 'புதிய புகார் பதிவு',
    'helpdesk.subject': 'தலைப்பு',
    'helpdesk.description': 'விவரம்',
    'helpdesk.priority': 'முன்னுரிமை',
    'helpdesk.submit': 'புகார் சமர்ப்பி',
    'helpdesk.add_reply': 'பதில் சேர்க்கவும்...',
    'helpdesk.select_ticket': 'உரையாடலை பார்க்க புகாரை தேர்ந்தெடுக்கவும்',
    'helpdesk.no_tickets': 'இதுவரை புகார் பதிவு இல்லை.',
    'helpdesk.attachment': 'இணைப்பு (விரும்பினால் படம்)',
    // Settings
    'settings.title': 'அமைப்புகள்',
    'settings.pricing': 'கட்டண விகிதம்',
    'settings.reminders': 'நினைவூட்டல்கள்',
    'settings.general': 'பொது',
    // Status
    'status.paid': 'செலுத்தப்பட்டது',
    'status.overdue': 'தாமதம்',
    'status.due_this_month': 'இந்த மாதம் நிலுவை',
    'status.cancelled': 'ரத்து செய்யப்பட்டது',
    'status.open': 'திறந்தது',
    'status.resolved': 'தீர்க்கப்பட்டது',
    'status.closed': 'மூடப்பட்டது',
    // Events
    'events.title': 'சமூக நிகழ்வுகள்',
    'events.no_events': 'வரவிருக்கும் நிகழ்வுகள் இல்லை.',
    // Reports
    'reports.title': 'நிதி அறிக்கைகள்',
    'reports.export': 'எக்செல் ஏற்றுமதி',
    'reports.apply_filter': 'வடிகட்டு பயன்படுத்து',
    'reports.period_income': 'காலகட்ட வருமானம்',
    'reports.period_expenses': 'காலகட்ட செலவு',
    // Upcoming dues
    'upcoming.title': 'வரவிருக்கும் நிலுவைகள்',
    'upcoming.member': 'உறுப்பினர்',
    'upcoming.paid_until': 'வரை செலுத்தப்பட்டது',
    'upcoming.outstanding': 'நிலுவை தொகை',
    'upcoming.no_records': 'வரவிருக்கும் அல்லது தாமதமான கட்டணங்கள் இல்லை! அனைத்து உறுப்பினர்களும் செலுத்தியுள்ளனர்.',
    // Audit logs
    'logs.title': 'தணிக்கை பதிவுகள்',
    // Notifications
    'notify.title': 'அறிவிப்பு அனுப்பு',
    'notify.send': 'உறுப்பினருக்கு அனுப்பு',
    'notify.broadcast': 'அனைவருக்கும் அனுப்பு',
    // Cash handover
    'cash.handover_request': 'பணம் கையளிப்பு கோரிக்கை',
    'cash.accept': 'ஏற்று & இருப்பு புதுப்பி',
    'cash.wants_handover': 'கையளிக்க விரும்புகிறார்',
    'cash.to_you': 'உங்களுக்கு.',
    // Ledger
    'ledger.title': 'பேரேடு கட்டண தேதிகள்',

    // Staff Management
    'staff.manage_desc': 'இவா்முகப்பில் உள்நுழையக்கூடிய கருவூலர்கள், செயலாளர்கள் மற்றும் கமிட்டி உறுப்பினர்களை நிர்வகிக்கவும்.',
    'staff.no_bearers': 'அலுவல் பொறுப்பாளர்கள் யாரும் இன்னும் சேர்க்கப்படவில்லை. உங்கள் முதல் கருவூலர் அல்லது செயலாளரைச் சேர்க்கவும்.',
    'staff.add_bearer': 'பொறுப்பாளர் சேர்',
    'staff.edit_bearer': 'பொறுப்பாளர் திருத்து',
    'staff.add_new_bearer': 'புதிய பொறுப்பாளர் சேர்',
    'staff.full_name': 'முழு பெயர் *',
    'staff.email': 'மின்னஞ்சல் *',
    'staff.mobile': 'கைபேசி *',
    'staff.password_label_edit': 'புதிய கடவுச்சொல் (மாற்றாமல் விட காலியாக விடவும்)',
    'staff.password_label_new': 'கடவுச்சொல் *',
    'staff.flat_no_optional': 'வீட்டு எண் (விரும்பினால்)',
    'staff.also_add_member': 'இவரை சமூக உறுப்பினராகவும் சேர்க்கவும் (உறுப்பினர் பட்டியலில் காண்பிக்கப்படும்)',
    'staff.associated_details': 'தொடர்புடைய உறுப்பினர் சுயவிவர விவரங்கள்',
    'staff.residence_type': 'வாழ்விட வகை *',
    'staff.bhk_option': 'BHK விருப்பம் *',
    'staff.bhk_specify': 'BHK விவரம்',
    'staff.bhk_option_label': 'BHK விருப்பம்',
    'staff.enable_common_maintenance': 'பொதுவான பராமரிப்பை இயக்கு (தேர்ந்தெடுக்கப்பட்டால், BHK மதிப்பிற்குப் பதிலாகப் பொதுவான மதிப்பை வசூலிக்கும்)',
    'staff.error_name': 'முழு பெயர் தேவை',
    'staff.error_email': 'மின்னஞ்சல் தேவை',
    'staff.error_mobile': 'கைபேசி எண் தேவை',
    'staff.error_mobile_digits': 'கைபேசி எண் 10 இலக்கமாக இருக்க வேண்டும்',
    'staff.error_bhk': 'BHK மதிப்பை உள்ளிடவும்',
    'staff.confirm_delete_title': 'அலுவல் பொறுப்பாளரை நீக்கு',
    'staff.confirm_delete_msg': 'அலுவல் பொறுப்பாளர்களிடமிருந்து "{name}" ஐ நீக்க விரும்புகிறீர்களா?',
    'staff.confirm_linked_title': 'இணைக்கப்பட்ட உறுப்பினர் விவரங்களை நீக்கு',
    'staff.confirm_linked_msg': '"{name}" உறுப்பினராகவும் பதிவு செய்யப்பட்டுள்ளார்.\n\nஅவரை உறுப்பினர் பட்டியலிலிருந்தும் நீக்க விரும்புகிறீர்களா?\n• இரண்டிலிருந்தும் (அலுவல் பொறுப்பாளர் & உறுப்பினர்) நீக்க OK கிளிக் செய்யவும்\n• அலுவல் பொறுப்பாளராக மட்டும் நீக்க Cancel கிளிக் செய்யவும் (உறுப்பினராக தொடர்வார்)',
    'staff.remove_both': 'இரண்டிலிருந்தும் நீக்கு',
    'staff.remove_only_staff': 'பொறுப்பாளராக மட்டும் நீக்கு',

    // Vendor Management
    'vendors.registered': '{count} சேவையாளர்(கள்) பதிவு செய்யப்பட்டுள்ளது',
    'vendors.edit': 'சேவையாளரை திருத்து',
    'vendors.add_new': 'புதிய சேவையாளர் சேர்',
    'vendors.name_label': 'சேவையாளர் / நிறுவன பெயர் *',
    'vendors.phone_label': 'தொலைபேசி / கைபேசி',
    'vendors.email_label': 'மின்னஞ்சல்',
    'vendors.address_label': 'முகவரி',
    'vendors.notes_label': 'குறிப்புகள்',
    'vendors.error_name': 'சேவையாளர் பெயர் தேவை',
    'vendors.error_phone': 'கைபேசி எண் 10 இலக்கமாக இருக்க வேண்டும்',
    'vendors.confirm_delete_title': 'சேவையாளரை நீக்கு',
    'vendors.confirm_delete_msg': 'சேவையாளர் "{name}" ஐ நீக்க வேண்டுமா? இது தொடர்புடைய செலவுகளைப் பாதிக்கலாம்.',
    'vendors.no_vendors': 'இன்னும் சேவையாளர்கள் சேர்க்கப்படவில்லை. பிளம்பர்கள், எலக்ட்ரீஷியன்கள் மற்றும் பிற சேவையாளர்களைச் சேர்க்கவும்.',

    // Expense Management
    'expenses.edit': 'செலவு திருத்து',
    'expenses.new': 'புதிய செலவு',
    'expenses.title_label': 'தலைப்பு *',
    'expenses.category_label': 'வகை *',
    'expenses.amount_label': 'தொகை (₹) *',
    'expenses.date_label': 'தேதி *',
    'expenses.payment_mode_label': 'கட்டண முறை *',
    'expenses.payment_mode_cash': 'பணம் (கையிருப்பிலிருந்து கழிக்கப்படும்)',
    'expenses.payment_mode_bank': 'வங்கி பரிமாற்றம்',
    'expenses.vendor_label': 'சேவையாளர் (விரும்பினால்)',
    'expenses.no_vendor': '— சேவையாளர் இல்லை —',
    'expenses.paid_by_member': 'உறுப்பினர் செலுத்தியது (தொகை கோரல்)',
    'expenses.select_member': 'உறுப்பினரைத் தேர்ந்தெடு',
    'expenses.no_member_society': '— இல்லை (சங்கம் செலுத்தியது) —',
    'expenses.reimbursement_method': 'திரும்பப் பெறும் முறை',
    'expenses.offset_dues': 'நிலுவைத் தொகையை ஈடுசெய் (முன்கூட்டியே செலுத்தப்பட்டது)',
    'expenses.cash_refund': 'பணத்தைத் திரும்பப்பெறுதல் (சங்கத்தின் பணத்தைக் கழித்தல்)',
    'expenses.notes_optional': 'குறிப்புகள் (விரும்பினால்)',
    'expenses.mark_recurring': 'தொடர்ச்சியான செலவாகக் குறிக்கவும் (மாதாந்திர)',
    'expenses.total_amount': 'மொத்தம்: ',
    'expenses.no_records_desc': 'செலவுகள் எதுவும் பதிவு செய்யப்படவில்லை. தொடங்க "செலவு சேர்" ஐக் கிளிக் செய்யவும்.',
    'expenses.confirm_delete_title': 'செலவை நீக்கு',
    'expenses.confirm_delete_msg': 'இந்த செலவை நீக்கவா?',
    'expenses.error_title': 'தலைப்பு தேவை',
    'expenses.error_amount': 'சரியான தொகையை உள்ளிடவும்',
    'expenses.error_delete': 'செலவை நீக்குவதில் பிழை',

    // Settings / Financial Cost Setup
    'settings.fy_cost_setup': 'நிதியாண்டு - ஆண்டு பராமரிப்பு கட்டண அமைப்பு',
    'settings.fy_cost_desc': 'வீடு மற்றும் வில்லாவிற்கு BHK வகைக்கு ஏற்ப வெவ்வேறு ஆண்டு பராமரிப்பு கட்டணங்களை அமைக்கவும். ஒவ்வொரு கலவையும் (வாழ்விட வகை + BHK) அதன் சொந்த கட்டணத்தைக் கொண்டிருக்கலாம்.',
    'settings.financial_year': 'நிதியாண்டு',
    'settings.residence_type': 'வாழ்விட வகை',
    'settings.residence_common': 'பொதுவான (அனைத்து உறுப்பினர்களும்)',
    'settings.residence_flat': 'வீடு (Flat)',
    'settings.residence_villa': 'வில்லா (Villa)',
    'settings.annual_fee': 'ஆண்டு பராமரிப்பு கட்டணம் (ரூ.)',
    'settings.set_bhk_fees': 'BHK வகையின் படி {residenceType} க்கான ஆண்டு பராமரிப்பு கட்டணங்களை அமைக்கவும்',
    'settings.bhk_fees_desc': 'ஒவ்வொரு BHK வகைக்கும் ஆண்டு பராமரிப்பு கட்டணத்தை குறிப்பிடவும். காலியாக உள்ள அல்லது 0 மதிப்புகள் புதுப்பிக்கப்படாது/அமைக்கப்படாது.',
    'settings.bhk_fee_label': '{bhk} BHK கட்டணம் (ரூ.)',
    'settings.custom_bhk_fees': 'தனிப்பயன் BHK பராமரிப்பு கட்டணங்கள் (விரும்பினால்)',
    'settings.add_custom_bhk': '+ தனிப்பயன் BHK சேர்',
    'settings.set_annual_fees': 'ஆண்டு பராமரிப்பு கட்டணங்களை அமை',
    'settings.configured_annual_fees': 'அமைக்கப்பட்ட ஆண்டு பராமரிப்பு கட்டணங்கள்',
    'settings.no_fees_configured': 'கட்டணங்கள் எதுவும் இன்னும் அமைக்கப்படவில்லை. தொடங்க மேலே உள்ள படிவத்தைப் பயன்படுத்தவும்.',
    'settings.common': 'பொதுவான',
    'settings.flat_by_bhk': 'வீடு - BHK படி',
    'settings.villa_by_bhk': 'வில்லா - BHK படி',
    'settings.delete_config_title': 'விலை அமைப்பை நீக்கு',
    'settings.delete_config_msg': 'இந்த விலை அமைப்பை நீக்க வேண்டுமா?',
    'settings.select_fy_error': 'தயவுசெய்து ஒரு நிதியாண்டைத் தேர்ந்தெடுக்கவும்',
    'settings.invalid_amount_error': 'தயவுசெய்து சரியான தொகையை உள்ளிடவும்',
    'settings.specify_bhk_error': 'தயவுசெய்து குறைந்தது ஒரு BHK வகைக்காவது கட்டணத் தொகையைக் குறிப்பிடவும்',
    'settings.config_success': 'பராமரிப்பு செலவு வெற்றிகரமாக அமைக்கப்பட்டது',
    'settings.config_deleted_success': 'விலை அமைப்பு வெற்றிகரமாக நீக்கப்பட்டது',

    // Masters Management
    'masters.title': 'முதன்மை தரவு மேலாண்மை',
    'masters.desc': 'கணினியில் பயன்படுத்தப்படும் கீழ்தோன்றும் (dropdown) மதிப்புகளை நிர்வகிக்கவும்.',
    'masters.service_types': 'சேவையாளர் வகைகள்',
    'masters.service_types_desc': 'வழங்குநர்கள் வழங்கக்கூடிய சேவைகளின் வகைகள் (எ.கா. பிளம்பிங், எலக்ட்ரிக்கல்)',
    'masters.designations': 'அலுவலர் பதவிகள்',
    'masters.designations_desc': 'அலுவலகப் பொறுப்பாளர்களுக்கான பதவிகள் (எ.கா. பொருளாளர், செயலாளர்)',
    'masters.expense_categories': 'செலவு வகைகள்',
    'masters.expense_categories_desc': 'செலவினங்களை வகைப்படுத்துவதற்கான பிரிவுகள் (எ.கா. பழுதுபார்ப்பு, பயன்பாடுகள்)',
    'masters.delete_title': 'முதன்மை உருப்படியை நீக்கு',
    'masters.delete_msg': 'பட்டியலில் இருந்து "{value}" ஐ நீக்கவா?',
    'masters.no_items': 'இன்னும் உருப்படிகள் இல்லை. மேலே உள்ள புதிய ஒன்றைச் சேர்க்கவும்.',

    // Helpdesk
    'helpdesk.all_status': 'அனைத்து நிலை',
    'helpdesk.status_open': 'திறந்தது',
    'helpdesk.status_in_progress': 'செயல்பாட்டில் உள்ளது',
    'helpdesk.status_resolved': 'தீர்க்கப்பட்டது',
    'helpdesk.status_closed': 'மூடப்பட்டது',
    'helpdesk.status_archived': 'காப்பகப்படுத்தப்பட்டது',
    'helpdesk.raised_by': 'பதிவு செய்தவர்: ',
    'helpdesk.attached_image': 'இணைக்கப்பட்ட படம்',
    'helpdesk.no_discussions': 'இதுவரை விவாதங்கள் இல்லை. கீழே உரையாடலைத் தொடங்கவும்.',
    'helpdesk.type_response': 'உங்கள் பதிலை இங்கே தட்டச்சு செய்யவும்...',
    'helpdesk.reply': 'பதில் அளி',
    'helpdesk.delete_ticket_title': 'உதவி மேசை புகாரை நீக்கு',
    'helpdesk.delete_ticket_msg': 'இந்த புகாரையும் அதன் அனைத்து விவாதங்களையும் நிரந்தரமாக நீக்க விரும்புகிறீர்களா?',
    'helpdesk.manage_desc': 'இந்த போர்டலில் இருந்து சமூக கவலைகள் மற்றும் உறுப்பினர் கோரிக்கைகளை நிர்வகிக்கவும்.',

    // Profile
    'profile.my_profile': 'என் சுயவிவரம் & கடவுச்சொல்',
    'profile.name': 'பெயர்',
    'profile.designation': 'பதவி',
    'profile.email': 'மின்னஞ்சல் முகவரி',
    'profile.mobile': 'கைபேசி எண்',
    'profile.save_btn': 'சுயவிவரம் & கடவுச்சொல் சேமி',
    'profile.primary_admin': 'முதன்மை நிர்வாகி',

    // Events

    'events.desc': 'சமூகத்தில் நிகழ்வுகள்/கூட்டங்களை திட்டமிட்டு நிர்வகிக்கவும். ஒரு நிகழ்வை உருவாக்குவது தானாகவே அனைத்து உறுப்பினர்களுக்கும் அறிவிப்பை அனுப்பும்.',
    'events.add': 'நிகழ்வைச் சேர்',
    'events.edit': 'நிகழ்வைத் திருத்து',
    'events.create_new': 'புதிய நிகழ்வை உருவாக்கு',
    'events.title_label': 'நிகழ்வின் தலைப்பு *',
    'events.date_label': 'நிகழ்வு தேதி & நேரம் *',
    'events.location_label': 'இடம் / அரங்கம்',
    'events.desc_label': 'நிகழ்வு விவரம் *',
    'events.venue': 'இடம்',
    'events.no_events_desc': 'வரவிருக்கும் நிகழ்வுகள் எதுவும் இன்னும் திட்டமிடப்படவில்லை. ஒன்றை உருவாக்க "நிகழ்வு சேர்" ஐக் கிளிக் செய்யவும்.',
    'events.delete_title': 'நிகழ்வை நீக்கு',
    'events.delete_msg': '"{title}" என்ற நிகழ்வை நீக்க விரும்புகிறீர்களா?',
    'events.error_required': 'தலைப்பு, விளக்கம் மற்றும் தேதி ஆகியவை தேவை.',
    'events.success_update': 'நிகழ்வு வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    'events.success_create': 'நிகழ்வு உருவாக்கப்பட்டு அனைத்து உறுப்பினர்களுக்கும் அறிவிக்கப்பட்டது!',
    'events.success_delete': 'நிகழ்வு வெற்றிகரமாக நீக்கப்பட்டது!',
    'events.error_delete': 'நிகழ்வை நீக்குவதில் பிழை',

    // Notifications
    'notify.send_manual': 'கையேடு அறிவிப்பை அனுப்பு',
    'notify.manual_desc': 'குறிப்பிட்ட உறுப்பினருக்கு இலக்கு அறிவிப்பை அனுப்பவும் அல்லது அனைத்து சமூக உறுப்பினர்களுக்கும் ஒளிபரப்பவும்.',
    'notify.send_to': 'அனுப்ப வேண்டியவர் *',
    'notify.all_members': '📢 அனைத்து உறுப்பினர்கள் (ஒளிபரப்பு)',
    'notify.specific_member': '👤 குறிப்பிட்ட உறுப்பினர்',
    'notify.select_member_label': 'உறுப்பினரைத் தேர்ந்தெடு *',
    'notify.title_label': 'அறிவிப்பு தலைப்பு *',
    'notify.message_label': 'விவரம் / செய்தி *',
    'notify.monthly_reminders': 'மாதாந்திர நிலுவை நினைவூட்டல்கள்',
    'notify.monthly_reminders_desc': 'ஒவ்வொரு மாதமும் 1-ஆம் தேதி தானாகவே இயங்கும். நீங்கள் இப்போது அதை கையேடாகவும் தூண்டலாம் — நிலுவைத் தொகை உள்ள உறுப்பினர்களுக்கு மட்டுமே அறிவிக்கப்படும்.',
    'notify.send_now': 'நிலுவை நினைவூட்டல்களை இப்போது அனுப்பு',
    'notify.paid_warning_title': 'உறுப்பினர் ஏற்கனவே பணம் செலுத்தியிருக்கலாம்',
    'notify.cancel_dont_send': 'ரத்து செய் — அனுப்ப வேண்டாம்',
    'notify.send_anyway': 'இருப்பினும் அனுப்பு',

    // Members Modals
    'members.register_desc': 'புதிய குடியிருப்பாளரை பதிவு செய்து அவர்களின் போர்டல் அணுகலை அமைக்கவும்',
    'members.general_details': '01. பொதுவான விவரங்கள்',
    'members.contact_access': '02. தொடர்பு & அணுகல்',
    'members.document_uploads': '03. ஆவணப் பதிவேற்றங்கள்',
    'members.initial_setup': '04. ஆரம்ப அமைப்பு / மூலதன நிதி',
    'members.custom_bhk': 'தனிப்பயன் BHK *',
    'members.enable_common_maintenance': 'பொதுவான பராமரிப்பை இயக்கு',
    'members.default_tenure': 'இயல்புநிலை கட்டணக் காலம் *',
    'members.active_from': 'உறுப்பினர் சேர்க்கை தேதி',
    'members.next_cycle_desc': 'அடுத்த கட்டணச் சுழற்சி இந்தத் தேதியிலிருந்து தொடங்கும்.',
    'members.old_dues': 'பழைய நிலுவைத் தொகைகள் (ரூ.)',
    'members.reg_year': 'பதிவு செய்த ஆண்டு *',
    'members.primary_contact': 'முதன்மை தொடர்பு (கட்டாயம்)',
    'members.primary_number': 'முதன்மை எண் *',
    'members.primary_email': 'முதன்மை மின்னஞ்சல் (விரும்பினால்)',
    'members.set_primary_password': 'முதன்மை உள்நுழைவு கடவுச்சொல்லை அமை (விரும்பினால்)',
    'members.primary_password_desc': 'கடவுச்சொல்லை அமைப்பது கைபேசி அல்லது மின்னஞ்சல் வழியாக முதன்மை தொடர்புக்கு உறுப்பினர் போர்டல் உள்நுழைவை இயக்கும்.',
    'members.secondary_contact': 'இரண்டாம் நிலை தொடர்பு (விரும்பினால்)',
    'members.secondary_number': 'இரண்டாம் நிலை எண் (விரும்பினால்)',
    'members.secondary_email': 'இரண்டாம் நிலை மின்னஞ்சல் (விரும்பினால்)',
    'members.set_secondary_password': 'இரண்டாம் நிலை உள்நுழைவு கடவுச்சொல்லை அமை (விரும்பினால்)',
    'members.secondary_password_desc': 'கடவுச்சொல்லை அமைப்பது கைபேசி அல்லது மின்னஞ்சல் வழியாக இரண்டாம் நிலை தொடர்புக்கு உறுப்பினர் போர்டல் உள்நுழைவை இயக்கும்.',
    'members.id_proof': 'அடையாளச் சான்று (ஆதார்/பான்)',
    'members.uploaded_id': 'பதிவேற்றப்பட்ட அடையாள ஆவணம்',
    'members.upload_image': 'படம்/புகைப்படம் பதிவேற்றவும்',
    'members.upload_pdf': 'PDF ஆவணத்தைப் பதிவேற்றவும்',
    'members.uploading_wait': '⏳ ஆவணம் பதிவேற்றப்படுகிறது, தயவுசெய்து காத்திருக்கவும்...',
    'members.initial_payment': 'ஆரம்ப கட்டணம் (ரூ.)',
    'members.payment_mode': 'கட்டண முறை',
    'members.payment_date': 'கட்டண தேதி',
    'members.payment_notes': 'கட்டணக் குறிப்புகள்',
    'members.add_btn': 'உறுப்பினர் சேர்',
    'members.edit_details': 'உறுப்பினர் விவரங்களைத் திருத்து',
    'members.edit_desc': 'குடியிருப்பாளர் சுயவிவரம், சான்றுகள் மற்றும் ஆவணங்களை மாற்றியமைக்கவும்',
    'members.status_label': 'நிலை *',
    'members.paid_until_label': 'இதுவரை செலுத்தப்பட்டது (மறைக்கப்பட்ட காலம்)',
    'members.next_cycle_edit_desc': 'அடுத்த கட்டணச் சுழற்சி இந்தத் தேதிக்குப் பிறகு தொடங்கும்.',
    'members.outstanding_dues_label': 'நிலுவைத் தொகைகள் (ரூ.)',
    'members.outstanding_dues_desc': 'இந்த உறுப்பினருக்கான தற்போதைய செலுத்தப்படாத நிலுவை/நிலுவைத் தொகை.',
    'members.change_primary_password': 'முதன்மை உள்நுழைவு கடவுச்சொல்லை மாற்று (விரும்பினால்)',
    'members.password_update_desc': 'புதிய கடவுச்சொல்லை உள்ளிட்டால் மட்டுமே கடவுச்சொல் புதுப்பிக்கப்படும்.',
    'members.change_secondary_password': 'இரண்டாம் நிலை உள்நுழைவு கடவுச்சொல்லை மாற்று (விரும்பினால்)',
    'members.update_btn': 'உறுப்பினரை புதுப்பி',

    // Payments Modals
    'payments.choose_member': '-- உறுப்பினரைத் தேர்ந்தெடுக்கவும் --',
    'payments.click_select': 'தேர்ந்தெடுக்க கிளிக் செய்யவும்',
    'payments.monthly': 'மாதாந்திர',
    'payments.quarterly': 'காலாண்டு',
    'payments.half_yearly': 'அரையாண்டு',
    'payments.annual': 'ஆண்டுவாரி',
    'payments.received_date': 'உறுப்பினரிடமிருந்து பெறப்பட்ட கட்டண தேதி',
    'payments.amount_received': 'பெறப்பட்ட தொகை (ரூ.)',
    'payments.early_discount_label': 'முன்கூட்டிய தள்ளுபடி (ரூ.)',
    'payments.late_fee_label': 'தாமதக் கட்டணம் (ரூ.)',
    'payments.total_amount_label': 'மொத்தத் தொகை (ரூ.)',
    'payments.ledger_date': 'பேரேட்டில் பதிவு செய்யப்பட்ட கட்டண தேதி',
    'payments.notes_placeholder': 'எ.கா. ரசீது எண், பரிவர்த்தனை ஐடி',
    'payments.custom_coverage': 'மேம்பட்டது: தனிப்பயன் காப்பீட்டுத் தேதிகள்',
    'payments.coverage_desc': 'தற்போதைய கட்டணத் தேதி அடிப்படையில் தானாகக் கணக்கிட காலியாக விடவும்.',
    'payments.coverage_start': 'காப்பீடு தொடக்கம் (விரும்பினால்)',
    'payments.coverage_end': 'காப்பீடு முடிவு (விரும்பினால்)',
    'payments.current_cash': 'உங்கள் தற்போதைய கையிருப்பு பணம்',
    'payments.transfer_type': 'பரிமாற்ற வகை',
    'payments.handover_to_admin': 'நிர்வாகியிடம் ஒப்படைக்கவும்',
    'payments.deposit_to_bank': 'வங்கி வைப்புத்தொகை',
    'payments.select_recipient': 'பெறுநர் நிர்வாகியைத் தேர்ந்தெடுக்கவும்',
    'payments.select_treasurer': '-- கருவூலரைத் தேர்ந்தெடுக்கவும் --',
    'payments.initiate_transfer': 'பரிமாற்றத்தைத் தொடங்குங்கள்',

    // New common / status keys
    'status.active': 'செயலில் உள்ளவர்',
    'status.inactive': 'செயலற்றவர்',
    'common.optional': 'விரும்பினால்',
    'common.image': 'படம்',
    'common.pdf': 'PDF',

    // New overview / dashboard keys
    'overview.total_collection': 'மொத்த வசூல்',
    'overview.this_month_income': 'இந்த மாதம்: ₹{amount}',
    'overview.this_month_expense': 'இந்த மாதம்: ₹{amount}',
    'overview.collection_expenses': 'வசூல் – செலவுகள்',
    'overview.your_share': 'உங்கள் பங்கு: ₹{amount}',
    'overview.vs_last_month': 'கடந்த மாதத்துடன் ஒப்பிடும்போது',
    'overview.financial_recon': 'நிதி சமரசம்',
    'overview.all_payment_modes': 'அனைத்து கட்டண முறைகளும்',
    'overview.all_recorded_expenses': 'பதிவுசெய்யப்பட்ட அனைத்து செலவுகளும்',
    'overview.collected_minus_expenses': 'வசூலிக்கப்பட்டது − செலவுகள்',
    'overview.physical_cash_avail': 'கையிருப்பு ரொக்க பணம்',
    'overview.cash_how_calculated': 'கையிருப்பு பணம் — கணக்கிடும் முறை',
    'overview.cash_collected': 'பணமாக வசூலிக்கப்பட்டது',
    'overview.cash_expenses': 'பணச் செலவுகள்',
    'overview.bank_deposited': 'வங்கியில் செலுத்தப்பட்டது',
    'overview.non_cash_collected': 'ரொக்கமல்லாதவை (UPI/வங்கி/காசோலை)',
    'overview.outstanding_dues_alert': '{count} உறுப்பினர்கள் ₹{amount} நிலுவை வைத்துள்ளனர்',
    'overview.view_members': 'உறுப்பினர்களைப் பார்க்க →',
    'overview.six_month_trend': '6 மாத வருமானம் மற்றும் செலவு போக்கு',
    'overview.collection': 'வசூல்',
    'overview.expenses_label': 'செலவுகள்',
    'overview.net': 'நிகரம்',
    'overview.expense_by_cat': 'வகை வாரியாக செலவுகள்',
    'overview.no_expense_recorded': 'இதுவரை செலவுகள் பதிவு செய்யப்படவில்லை',
    'overview.recent_collections': 'சமீபத்திய வசூல்கள்',
    'overview.no_payment_recorded': 'கட்டணங்கள் எதுவும் இன்னும் பதிவு செய்யப்படவில்லை.',
    'overview.cash_holders': 'கையிருப்பு பணம் — வைத்திருப்பவர்கள்',
    'overview.no_cash_data': 'கையிருப்பு பண விபரங்கள் இல்லை.',
    'overview.you': 'நீங்கள்',
    'overview.total': 'மொத்தம்',

    // New members keys
    'members.society_members': 'சங்க உறுப்பினர்கள்',
    'members.search_placeholder': 'பெயர், வீடு, கைபேசி கொண்டு தேடு...',
    'members.export_excel': 'எக்செல் ஏற்றுமதி',
    'members.template': 'மாதிரி படிவம்',
    'members.bulk_import': 'கூட்டாக இறக்குமதி',
    'members.contact_info': 'தொடர்பு விபரம்',
    'members.no_matching_found': 'பொருந்தும் உறுப்பினர்கள் யாரும் இல்லை',
    'members.widen_search': 'உங்கள் தேடல் சொற்களை விரிவுபடுத்தவும் அல்லது தேடலை அழிக்கவும்',
    'members.photo': 'புகைப்படம்',
    'members.id_proof_tag': 'அடையாள சான்று',
    'members.click_view_photo': 'சுயவிவரப் புகைப்படத்தைப் பார்க்க கிளிக் செய்க',
    'members.click_view_id': 'அடையாள சான்றைப் பார்க்க கிளிக் செய்க',
    'members.no_email': 'மின்னஞ்சல் இல்லை',
    'members.no_fy_fee': 'நிதியாண்டு கட்டணம் இல்லை',
    'members.unpaid_periods_msg': '{count} {period} @ {rate}',
    'members.history_btn': 'வரலாறு',
    'members.mark_vacant': 'வீடு காலியாக உள்ளது எனக் குறிக்கவும்',
    'members.vacated_pending_dues': 'நிலுவையுடன் வெளியேறிய உறுப்பினர்கள்',
    'members.vacated_pending_desc': 'இந்த உறுப்பினர்கள் வீட்டை காலி செய்துள்ளனர் ஆனால் இன்னும் நிலுவை தொகையை செலுத்த வேண்டியுள்ளது.',
    'members.other_custom': 'மற்றவை / தனிப்பயன்',

    // New payments keys
    'payments.payment_history': 'கட்டண வரலாறு',
    'payments.export_excel': 'எக்செல் ஏற்றுமதி',
    'payments.record_payment': 'கட்டணம் பதிவு செய்',
    'payments.onboarding': 'சேர்க்கை',
    'payments.view_receipt': 'ரசீது காண்க',
    'payments.edit_payment': 'கட்டணம் திருத்து',
    'payments.cancel_payment': 'கட்டணம் ரத்து செய்',
    'payments.mode_cash': 'பணம் (CASH)',
    'payments.mode_bank': 'வங்கி பரிமாற்றம்',
    'payments.mode_upi': 'UPI / QR',
    'payments.mode_cheque': 'காசோலை',
    'payments.total_paid': 'மொத்தம் செலுத்தப்பட்டது',
    'payments.outstanding': 'நிலுவை',
    'payments.receipts_count': 'ரசீதுகள்',
    'payments.fy': 'நிதியாண்டு',
    'payments.coverage': 'காப்பீடு காலம்',
    'payments.status': 'நிலை',
    'payments.maintenance_receipt': 'பராமரிப்பு கட்டண ரசீது',
    'payments.generated_on': 'உருவாக்கப்பட்டது',
    'payments.collected_by': 'வழங்கியவர்',
    'payments.download_pdf': 'PDF பதிவிறக்கம்',
    'payments.select_member': 'உறுப்பினரைத் தேர்ந்தெடு',
    'payments.category_maintenance': 'பராமரிப்பு (Maintenance)',
    'payments.category_event': 'நிகழ்வு கட்டணம்',
    'payments.category_corpus': 'மூலதன நிதி',
    'payments.category_water': 'தண்ணீர் நிலுவை',
    'payments.category_other': 'இதர',
    'payments.notes': 'குறிப்பு / குறிப்புகள்',
    'payments.edit_payment_title': 'கட்டணம் திருத்து — {receipt}',
    'payments.transfer_cash': 'பணம் ஒப்படைப்பு / பரிமாற்றம்',
    'payments.transfer_notes_placeholder': 'எ.கா. வாராந்திர வங்கி வைப்புத்தொகைக்கு',

    // New ledger reconciliation keys
    'ledger.ledger_payment_dates': 'பேரேடு கட்டண தேதிகள்',
    'ledger.compare_dates_desc': 'உறுப்பினரிடமிருந்து கட்டணம் பெறப்பட்ட தேதியையும் பேரேட்டில் பதிவுசெய்யப்பட்ட தேதியையும் ஒப்பிடுக.',
    'ledger.received_date_member': 'பெறப்பட்ட தேதி (உறுப்பினர்)',
    'ledger.recorded_date_ledger': 'பதிவுசெய்யப்பட்ட தேதி (பேரேடு)',
    'ledger.not_recorded': 'பதிவு செய்யப்படவில்லை',
    'ledger.no_records': 'கட்டணப் பதிவுகள் எதுவும் இல்லை',

    // New reports keys
    'reports.financial_reports': 'நிதி அறிக்கைகள்',
    'reports.generate_analyze': 'நிதி அறிக்கைகளை உருவாக்கி பகுப்பாய்வு செய்யுங்கள்',
    'reports.export_excel': 'எக்செல் ஏற்றுமதி',
    'reports.month': 'மாதம்',
    'reports.all_months': 'அனைத்து மாதங்களும்',
    'reports.year': 'ஆண்டு',
    'reports.start_date': 'தொடக்க தேதி',
    'reports.end_date': 'முடிவு தேதி',
    'reports.period_surplus_deficit': 'காலகட்ட உபரி / பற்றாக்குறை',
    'reports.balance_sheet_status': 'இருப்புநிலைக் குறிப்பு நிலை',
    'reports.balanced': 'சமநிலைப்பட்டது',
    'reports.diff': 'வேறுபாடு: ₹{amount}',
    'reports.income_expenditure_stmt': 'வருமானம் மற்றும் செலவு அறிக்கை',
    'reports.balance_sheet': 'இருப்புநிலைக் குறிப்பு',
    'reports.no_transactions': 'பரிவர்த்தனைகள் எதுவும் இல்லை',
    'reports.no_transactions_desc': 'தேர்ந்தெடுக்கப்பட்ட காலத்திற்கு வருமானம் அல்லது செலவுகள் ஏதும் இல்லை: {period}',
    'reports.dr': 'பற்று',
    'reports.cr': 'வரவு',
    'reports.expenditure': 'செலவு',
    'reports.income': 'வருமானம்',
    'reports.total': 'மொத்தம்',
    'reports.as_at': 'வரை: {date}',
    'reports.liabilities': 'பொறுப்புகள்',
    'reports.assets': 'சொத்துக்கள்',

    // New logs keys
    'logs.audit_logs': 'தணிக்கை பதிவுகள்',
    'logs.of_entries': '{total} பதிவுகளில் {count} காட்டு',
    'logs.from_date': 'தொடக்க தேதி',
    'logs.to_date': 'முடிவு தேதி',
    'logs.office_bearer': 'அலுவல் பொறுப்பாளர்',
    'logs.all_office_bearers': 'அனைத்து பொறுப்பாளர்களும்',
    'logs.show_logs': 'பதிவுகளைக் காட்டு',
    'logs.show_all_logs': 'அனைத்து பதிவுகளையும் காட்டு',
    'logs.clear_filters': 'வடிகட்டிகளை அழி',
    'logs.timestamp': 'நேரமுத்திரை',
    'logs.user': 'பயனர்',
    'logs.action': 'செயல்',
    'logs.details': 'விவரங்கள்',
    'logs.no_match': 'உங்கள் வடிகட்டிகளுடன் தணிக்கை பதிவுகள் எதுவும் பொருந்தவில்லை.',
    'logs.set_filters_prompt': 'வடிகட்டிகளை அமைத்து பதிவுகளைக் காட்டு என்பதை அழுத்தவும்',
    'logs.use_filters_desc': 'தணிக்கை பதிவுகளை சுருக்க மேலே உள்ள வடிகட்டிகளைப் பயன்படுத்தவும், பின் முடிவுகளை ஏற்ற பொத்தானை அழுத்தவும்.',

    // New settings keys
    'settings.settings_hub': 'அமைப்புகள் மையம்',
    'settings.config_desc': 'சங்கத்தின் முன்னுரிமைகளை அமைக்கவும்',
    'settings.pricing_fees': 'கட்டணங்கள் & கட்டண விகிதம்',
    'settings.auto_reminders': 'தானியங்கி நினைவூட்டல்கள்',
    'settings.early_discount': 'முன்கூட்டியே செலுத்தும் தள்ளுபடி',
    'settings.late_fee': 'தாமதக் கட்டணம்',
    'settings.fy_setup': 'நிதியாண்டு அமைப்பு',
    'settings.system_masters': 'முதன்மை அமைப்புகள்',
    'settings.society_settings_pricing': 'சங்க அமைப்புகள் (கட்டண முதன்மை)',
    'settings.pricing_desc': 'கட்டண திட்டங்களுக்கான அடிப்படை விகிதங்கள் மற்றும் தள்ளுபடிகளை வரையறுக்கவும்.',
    'settings.base_monthly': 'அடிப்படை மாதாந்திர தொகை (₹)',
    'settings.quarterly_amt': 'காலாண்டு தொகை (₹)',
    'settings.half_yearly_amt': 'அரையாண்டு தொகை (₹)',
    'settings.annual_amt': 'வருடாந்திர தொகை (₹)',
    'settings.save_pricing': 'கட்டண அமைப்புகளை சேமி',
    'settings.auto_reminder_settings': 'தானியங்கி நினைவூட்டல் அமைப்புகள்',
    'settings.auto_reminder_desc': 'நிலுவைத் தொகைகளுக்கான நினைவூட்டல் மின்னஞ்சல்கள் மற்றும் விழிப்பூட்டல்களைத் தானியங்குபடுத்துங்கள்.',
    'settings.monthly_maint_reminder': 'மாதாந்திர பராமரிப்பு நினைவூட்டல்',
    'settings.monthly_reminder_desc': 'மாதத்தில் குறிப்பிட்ட இடைவெளியில் செயலில் உள்ள உறுப்பினர்களுக்கு தானாகவே நினைவூட்டல்களை அனுப்பவும்.',
    'settings.frequency_times': 'அதிர்வெண் (முறைகள்)',
    'settings.interval_days': 'இடைவெளி (நாட்கள்)',
    'settings.max_times_notify': 'கட்டண மாதத்தில் அறிவிக்க வேண்டிய அதிகபட்ச முறைகள்.',
    'settings.days_between_reminders': 'நினைவூட்டல்களுக்கு இடைப்பட்ட நாட்கள்.',
    'settings.overdue_dues_reminder': 'நிலுவைத் தொகை நினைவூட்டல்',
    'settings.overdue_reminder_desc': 'ஒரு உறுப்பினருக்கு நிலுவைத் தொகை இருந்தால், அது தீர்க்கப்படும் வரை அவ்வப்போது அறிவிப்புகளைத் தானாகவே அனுப்பவும்.',
    'settings.days_between_overdue_desc': 'நினைவூட்டல்களுக்கு இடைப்பட்ட நாட்கள். தொடர்ச்சியாக செலுத்தப்படாத மாதங்களுக்கு மாதாந்திர மின்னஞ்சல் விழிப்புணர்வு அனுப்பப்படும்.',
    'settings.save_reminders': 'நினைவூட்டல் அமைப்புகளை சேமி',
    'settings.early_payment_discount': 'முன்கூட்டியே செலுத்தும் தள்ளுபடி (விரும்பினால்)',
    'settings.early_discount_desc': 'குறிப்பிட்ட தேதிக்கு முன் பணம் செலுத்தும் உறுப்பினர்களுக்கு தள்ளுபடி வழங்கவும்.',
    'settings.discount_cutoff': 'தள்ளுபடிக்கான கடைசி தேதி',
    'settings.discount_cutoff_desc': 'இந்தத் தேதிக்கு முன் பெறப்படும் \'பராமரிப்பு\' கட்டணங்களுக்கு தானாகவே தள்ளுபடி பயன்படுத்தப்படும்.',
    'settings.discount_amount': 'தள்ளுபடி தொகை (₹)',
    'settings.discount_amount_desc': 'கணக்கிடப்பட்ட மொத்த கட்டணத்திலிருந்து கழிக்கப்படும் தட்டையான தொகை.',
    'settings.save_discount': 'தள்ளுபடி அமைப்புகளை சேமி',
    'settings.late_fee_settings': 'தாமதக் கட்டண அமைப்புகள் (விரும்பினால்)',
    'settings.late_fee_settings_desc': 'குறிப்பிட்ட தேதிக்குப் பின் பெறப்படும் பராமரிப்புக் கட்டணங்களுக்குத் தாமதக் கட்டணத்தை அமைக்கவும்.',
    'settings.active_late_fee_info': 'செயலில் உள்ள அமைப்புகள்: ஒவ்வொரு மாதமும் {day}-ஆம் தேதிக்கு மேல் தாமதக் கட்டணம் ₹{amount} வசூலிக்கப்படும்.',
    'settings.no_active_late_fee': 'செயலில் உள்ள தாமதக் கட்டண அமைப்புகள் எதுவும் இல்லை. தாமதக் கட்டணம் கணக்கிடப்படாது.',
    'settings.late_fee_cutoff': 'தாமதக் கட்டண கடைசி தேதி',
    'settings.late_fee_cutoff_desc': 'இந்தத் தேதிக்குப் பின் பெறப்படும் \'பராமரிப்பு\' கட்டணங்களுக்குத் தானாகவே தாமதக் கட்டணம் விதிக்கப்படும்.',
    'settings.late_fee_per_month': 'மாதாந்திர தாமதக் கட்டணம் (₹)',
    'settings.late_fee_per_month_desc': 'மாதந்தோறும் வசூலிக்கப்படும் தட்டையான கட்டணம். தனிப்பயன் காப்பீட்டுத் தேதிகளுக்கு, இது மூடப்பட்ட மாதங்களின் எண்ணிக்கையால் பெருக்கப்படுகிறது.',
    'settings.save_late_fee': 'தாமதக் கட்டண அமைப்புகளை சேமி',

    // New upcoming keys
    'upcoming.upcoming_overdue': 'வரவிருக்கும் & நிலுவைக் கட்டணங்கள்',
    'upcoming.monitor_manage': 'உறுப்பினர்களின் பராமரிப்பு நிலுவைகளைக் கண்காணித்து நிர்வகிக்கவும்',
    'upcoming.calculate_dues_by': 'இதன்படி நிலுவையைக் கணக்கிடு:',
    'upcoming.calc_db': 'நிலுவைத் தொகைகள் (DB)',
    'upcoming.calc_monthly': 'மாதாந்திர அடிப்படையில்',
    'upcoming.calc_quarterly': 'காலாண்டு அடிப்படையில்',
    'upcoming.calc_half_yearly': 'அரையாண்டு அடிப்படையில்',
    'upcoming.calc_annual': 'வருடாந்திர அடிப்படையில்',
    'upcoming.download_dues_list': 'நிலுவைப் பட்டியலை பதிவிறக்கு',
    'upcoming.dynamic_dues_info': 'அமைக்கப்பட்ட ஆண்டு கட்டணங்களைப் பயன்படுத்தி {mode} சுழற்சி அடிப்படையில் மாறும் வகையில் கணக்கிடப்பட்ட நிலுவைகளைக் காட்டுகிறது.',
    'upcoming.flat_no_col': 'வீட்டு எண்',
    'upcoming.member_col': 'உறுப்பினர்',
    'upcoming.paid_until_col': 'வரை செலுத்தப்பட்டது',
    'upcoming.outstanding_dues_col': 'நிலுவைத் தொகை',
    'upcoming.status_col': 'நிலை',
    'upcoming.annual_fee_not_configured': 'நிதியாண்டு {year}-க்கு ஆண்டு கட்டணம் இன்னும் அமைக்கப்படவில்லை',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language') as Language | null;
    return saved === 'en' || saved === 'ta' ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string, defaultValue?: string): string =>
    translations[language][key] ?? translations['en'][key] ?? defaultValue ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
